![](images/la.jpg)

### Load in NumPy (remember to pip install numpy first)

In [14]:
import numpy as np

### The Basics

In [20]:
arr = np.array([[1,4,7],[2,3,5],[2,3,5],[2,3,5]])
print(arr)

[[1 4 7]
 [2 3 5]
 [2 3 5]
 [2 3 5]]


In [35]:
# create an integer array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [28]:
# create a float array
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]
 [6. 5. 4.]]


In [26]:
# Get Dimension
arr.ndim

2

In [29]:
# Get Shape
b.shape

(3, 3)

In [30]:
# Get Type
a.dtype

dtype('int32')

In [31]:
# Get total size
a.nbytes

12

In [36]:
# Get number of elements
a.size

5

### Accessing/Changing specific elements, rows, columns, etc

In [38]:
arr = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [42]:
# Get a specific element [row, column]
arr[1,6]

14

In [46]:
# Get a specific row 
arr[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [50]:
# Get a specific column
arr[:, 4]

array([ 5, 12])

In [56]:
arr[0,1:-1:3]

array([2, 5])

In [58]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:1]

array([2, 3, 4, 5, 6])

In [24]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

### Initializing Different Types of Arrays

In [40]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [44]:
# Any other number
np.full((2,2), 99)

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [49]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [56]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.07805642, 0.53385716],
       [0.02494273, 0.99955252],
       [0.48588042, 0.91247437],
       [0.27779213, 0.16597751]])

In [73]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-2, -4, -4],
       [ 6,  6,  3],
       [ 3,  2,  2]])

In [61]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [12]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

# output[1:-1,1:-1] = z
# print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


##### Be careful when copying arrays!!!

In [62]:
# Copy an Array
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(b)

[100   2   3]


### Mathematics

In [63]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
# array to array addition

In [64]:
a + 2

array([3, 4, 5, 6])

In [65]:
a - 2

array([-1,  0,  1,  2])

In [66]:
a * 2

array([2, 4, 6, 8])

In [67]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [68]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [69]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [70]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [71]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [72]:
np.tanh(a)

array([0.76159416, 0.96402758, 0.99505475, 0.9993293 ])

In [73]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [74]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

##### Lists and Arrays

In [81]:
# create a list
lst = [1,2,3,4,5,6]
print(type(lst))

<class 'list'>


In [84]:
# contact a list
newlst = [7,8,9]
lst+newlst

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# append method

In [ ]:
# adding lists
lst + lst

In [ ]:
# Scalar Multiplication
lst * 4

##### Linear Algebra

In [127]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [132]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [133]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [85]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
np.min(stats)

1

In [88]:
np.max(stats, axis=1)

array([3, 6])

In [89]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [151]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [158]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [164]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [179]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [196]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])